#Write a progrm to display 
print("--------------------------------------------------------------------")
print("|                                                                  |")
print("|                                                                  |")
print("|                   Alvin  Development Hub                         |")
print("|                                                                  |")
print("|                     Fast &  Reliable                             |")
print("|                                                                  |")
print("|         Well versed in the top 5 programming languages           |")
print("|                                                                  |")
print("|         Started with the vision to make work easier              |")
print("|                           Est. 2016                              |")
print("|                                                                  |")
print("|         Contact 0744856578/alvindevelopmenthub.com               |")
print("|                                                                  |")
print("|                                                                  |")
print("|                                                                  |")  
print("--------------------------------------------------------------------")