#design triangle 
print("                                      /  \                                                  ")
print("                                     /    \                                                 ")
print("                                    /      \                                               ")
print("                                   /        \                                              ")
print("                                  /          \                                             ")
print("                                 /            \                                            ")
print("                                /              \                                           ")
print("                               /                \                                          ")
print("                              /                  \                                         ")
print("                             /                    \                                        ")
print("                             ----------------------                                        ")